# Generated by Django 4.0.4 on 2022-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orders_customer_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
