# Generated by Django 4.0.4 on 2022-04-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_orders_customer_alter_orders_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='name',
            new_name='customer',
        ),
    ]
